CREATE TABLE PLAYERS(
	PLAYER_ID INT NOT NULL AUTO_INCREMENT,
    PLAYER_NAME VARCHAR(50) NOT NULL,
    PLAYER_DOB DATE NOT NULL,
    PLAYER_NATIONALITY VARCHAR(50) NOT NULL,
    PLAYER_PIC_URL VARCHAR(255) NOT NULL,
    PLAYER_FLAG_URL VARCHAR(255) NOT NULL,
    
    PRIMARY KEY(PLAYER_ID)
);

CREATE TABLE ON_FIELD_STATS(
	PLAYER_ID INT,
    PAC INT,
    SHO INT,
    PAS INT,
    DRI INT,
    DEF INT,
    PHY INT,
	
    PRIMARY KEY(PLAYER_ID),
    CONSTRAINT FK_PLAYERS FOREIGN KEY (PLAYER_ID)
    REFERENCES PLAYERS(PLAYER_ID)
);

CREATE TABLE GK_STATS(
	PLAYER_ID INT,
    GK_DIV INT,
    GK_HAN INT,
    GK_KIC INT,
    GK_REF INT,
    GK_SPD INT,
    GK_POS INT,
    
    PRIMARY KEY(PLAYER_ID),
    CONSTRAINT FK_GK FOREIGN KEY (PLAYER_ID)
    REFERENCES PLAYERS(PLAYER_ID)
);

